name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "-D warnings"
      JWT_SECRET: "test"
    
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: "1.67.1"
        components: rustfmt
    - uses: actions/checkout@v3
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: Swatinem/rust-cache@v2
    - name: Check fmt
      run: cargo fmt -- --check
    - name: Check all targets
      run: cargo check --all --all-targets --all-features